logging:
  level:
    io.jokerr.spring.sandbox.demo: debug

spring:
  banner:
    location: classpath:/bannername.txt
  h2:
    console:
      enabled: true # enables http://localhost:8080/h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  output:
    ansi:
      enabled: always

management:
  endpoints:
    web:
      exposure:
        include: health,info,widget

--- # test config
spring:
  config:
    activate:
      on-profile: test

logging:
  level:
    io.jokerr.spring.sandbox.demo: info


--- # prod config
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: false
  output:
    ansi:
      enabled: never

logging:
  level:
    io.jokerr.spring.sandbox.demo: error
