logging:
  level:
    io.jokerr.spring.sandbox.demo: trace

spring:
  banner:
    location: classpath:/bannername.txt
  h2:
    console:
      enabled: true # enables http://localhost:8080/h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  output:
    ansi:
      enabled: always

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,info,widget
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
  health:
    defaults:
      enabled: false
    diskspace:
      enabled: true
    ping:
      enabled: true
    livenessstate: # see https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints.kubernetes-probes
      enabled: true
    readinessstate:
      enabled: true

--- # test config
spring:
  config:
    activate:
      on-profile: test
  sql:
    init:
      mode: never # see https://www.baeldung.com/spring-boot-data-sql-and-schema-sql for more info on embedded db

logging:
  level:
    io.jokerr.spring.sandbox.demo: info


--- # prod config
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: false
  output:
    ansi:
      enabled: never
  sql:
    init:
      mode: never

logging:
  level:
    io.jokerr.spring.sandbox.demo: warn

management:
  endpoint:
    health:
      show-details: never